insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (1, 'VP Quality Control', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (2, 'Marketing Manager', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (3, 'Operator', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (4, 'Director of Sales', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (5, 'Marketing Assistant', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (6, 'Electrical Engineer', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (7, 'Associate Professor', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (8, 'Mechanical Systems Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (9, 'Compensation Analyst', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (10, 'Research Assistant III', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (11, 'Cost Accountant', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (12, 'Information Systems Manager', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (13, 'VP Product Management', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (14, 'Statistician I', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (15, 'Paralegal', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (16, 'Environmental Specialist', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (17, 'Occupational Therapist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (18, 'Software Engineer I', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (19, 'Sales Representative', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (20, 'Nuclear Power Engineer', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (21, 'Graphic Designer', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (22, 'Financial Analyst', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (23, 'Executive Secretary', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (24, 'Web Developer I', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (25, 'Analog Circuit Design manager', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (26, 'Social Worker', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (27, 'Compensation Analyst', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (28, 'Environmental Tech', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (29, 'Database Administrator IV', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (30, 'Programmer Analyst IV', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (31, 'Information Systems Manager', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (32, 'Accountant III', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (33, 'Director of Sales', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (34, 'Actuary', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (35, 'Software Consultant', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (36, 'Business Systems Development Analyst', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (37, 'Staff Scientist', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (38, 'Financial Advisor', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (39, 'VP Product Management', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (40, 'Financial Advisor', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (41, 'Internal Auditor', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (42, 'Statistician IV', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (43, 'Computer Systems Analyst IV', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (44, 'VP Accounting', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (45, 'VP Marketing', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (46, 'Analog Circuit Design manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (47, 'Mechanical Systems Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (48, 'Recruiter', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (49, 'Senior Sales Associate', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (50, 'Professor', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (51, 'Recruiting Manager', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (52, 'Sales Associate', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (53, 'Quality Engineer', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (54, 'Staff Scientist', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (55, 'Community Outreach Specialist', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (56, 'Recruiting Manager', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (57, 'Statistician II', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (58, 'Accountant II', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (59, 'Teacher', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (60, 'Senior Developer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (61, 'Database Administrator II', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (62, 'Research Nurse', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (63, 'Staff Scientist', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (64, 'Tax Accountant', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (65, 'Environmental Specialist', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (66, 'Registered Nurse', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (67, 'Chemical Engineer', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (68, 'Marketing Assistant', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (69, 'Nurse Practicioner', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (70, 'Occupational Therapist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (71, 'Help Desk Technician', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (72, 'Financial Advisor', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (73, 'Legal Assistant', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (74, 'VP Accounting', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (75, 'Physical Therapy Assistant', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (76, 'Marketing Assistant', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (77, 'Recruiting Manager', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (78, 'Assistant Media Planner', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (79, 'Assistant Manager', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (80, 'Senior Editor', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (81, 'Sales Representative', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (82, 'Civil Engineer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (83, 'Community Outreach Specialist', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (84, 'Software Consultant', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (85, 'Help Desk Operator', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (86, 'Research Nurse', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (87, 'Nuclear Power Engineer', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (88, 'Social Worker', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (89, 'Account Coordinator', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (90, 'Director of Sales', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (91, 'Analyst Programmer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (92, 'Editor', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (93, 'Recruiter', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (94, 'Internal Auditor', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (95, 'VP Sales', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (96, 'Account Representative I', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (97, 'Mechanical Systems Engineer', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (98, 'Geologist II', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (99, 'Operator', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (100, 'Chemical Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (101, 'Web Developer II', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (102, 'Account Representative III', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (103, 'Civil Engineer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (104, 'Dental Hygienist', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (105, 'Engineer II', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (106, 'Information Systems Manager', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (107, 'Recruiting Manager', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (108, 'Civil Engineer', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (109, 'Media Manager I', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (110, 'Research Nurse', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (111, 'Environmental Tech', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (112, 'Operator', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (113, 'VP Product Management', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (114, 'Human Resources Assistant I', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (115, 'Compensation Analyst', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (116, 'Cost Accountant', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (117, 'Tax Accountant', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (118, 'Sales Representative', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (119, 'Nurse', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (120, 'Geological Engineer', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (121, 'Media Manager IV', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (122, 'Assistant Manager', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (123, 'Web Developer IV', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (124, 'Senior Financial Analyst', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (125, 'Geological Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (126, 'Health Coach IV', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (127, 'Human Resources Manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (128, 'Research Assistant IV', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (129, 'Statistician II', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (130, 'Environmental Specialist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (131, 'Paralegal', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (132, 'Junior Executive', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (133, 'Occupational Therapist', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (134, 'Software Test Engineer II', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (135, 'Office Assistant III', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (136, 'Software Consultant', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (137, 'Quality Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (138, 'Electrical Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (139, 'VP Sales', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (140, 'Human Resources Manager', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (141, 'Help Desk Technician', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (142, 'Operator', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (143, 'VP Product Management', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (144, 'Software Engineer I', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (145, 'Software Engineer IV', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (146, 'Marketing Assistant', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (147, 'Administrative Officer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (148, 'Computer Systems Analyst II', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (149, 'Safety Technician I', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (150, 'Payment Adjustment Coordinator', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (151, 'Teacher', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (152, 'Quality Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (153, 'Biostatistician I', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (154, 'Database Administrator I', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (155, 'Associate Professor', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (156, 'Health Coach II', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (157, 'Project Manager', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (158, 'Clinical Specialist', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (159, 'VP Sales', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (160, 'Mechanical Systems Engineer', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (161, 'Accounting Assistant IV', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (162, 'Legal Assistant', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (163, 'Senior Financial Analyst', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (164, 'General Manager', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (165, 'Account Coordinator', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (166, 'Senior Editor', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (167, 'Computer Systems Analyst III', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (168, 'Design Engineer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (169, 'GIS Technical Architect', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (170, 'Research Associate', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (171, 'Web Designer II', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (172, 'Chief Design Engineer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (173, 'General Manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (174, 'Software Consultant', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (175, 'Graphic Designer', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (176, 'Project Manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (177, 'Technical Writer', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (178, 'Developer II', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (179, 'Accounting Assistant III', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (180, 'Pharmacist', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (181, 'Teacher', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (182, 'Account Executive', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (183, 'Design Engineer', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (184, 'GIS Technical Architect', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (185, 'VP Sales', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (186, 'Junior Executive', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (187, 'Actuary', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (188, 'Programmer IV', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (189, 'Help Desk Technician', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (190, 'VP Sales', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (191, 'Staff Accountant I', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (192, 'Automation Specialist IV', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (193, 'Engineer I', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (194, 'Human Resources Manager', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (195, 'Payment Adjustment Coordinator', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (196, 'Editor', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (197, 'VP Product Management', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (198, 'Teacher', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (199, 'Product Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (200, 'Director of Sales', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (201, 'Senior Financial Analyst', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (202, 'Financial Advisor', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (203, 'Media Manager III', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (204, 'Computer Systems Analyst II', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (205, 'Recruiter', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (206, 'Nurse Practicioner', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (207, 'Administrative Assistant II', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (208, 'Geologist II', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (209, 'Professor', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (210, 'Structural Engineer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (211, 'Human Resources Assistant I', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (212, 'Dental Hygienist', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (213, 'Analog Circuit Design manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (214, 'VP Sales', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (215, 'Electrical Engineer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (216, 'Human Resources Manager', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (217, 'Structural Engineer', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (218, 'Occupational Therapist', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (219, 'VP Quality Control', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (220, 'Nuclear Power Engineer', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (221, 'Nurse Practicioner', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (222, 'Pharmacist', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (223, 'VP Quality Control', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (224, 'Senior Sales Associate', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (225, 'Marketing Assistant', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (226, 'Librarian', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (227, 'Physical Therapy Assistant', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (228, 'Assistant Manager', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (229, 'Administrative Assistant IV', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (230, 'Executive Secretary', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (231, 'Data Coordiator', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (232, 'GIS Technical Architect', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (233, 'Computer Systems Analyst III', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (234, 'Quality Engineer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (235, 'Administrative Assistant II', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (236, 'Assistant Media Planner', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (237, 'Speech Pathologist', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (238, 'Assistant Professor', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (239, 'Marketing Manager', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (240, 'Project Manager', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (241, 'Structural Analysis Engineer', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (242, 'Developer I', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (243, 'Web Designer IV', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (244, 'Structural Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (245, 'Recruiting Manager', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (246, 'Sales Representative', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (247, 'Geological Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (248, 'Human Resources Manager', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (249, 'Mechanical Systems Engineer', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (250, 'Editor', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (251, 'Recruiter', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (252, 'Clinical Specialist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (253, 'Web Developer III', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (254, 'Administrative Assistant IV', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (255, 'Recruiter', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (256, 'VP Quality Control', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (257, 'Media Manager II', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (258, 'Programmer II', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (259, 'Director of Sales', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (260, 'Business Systems Development Analyst', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (261, 'Executive Secretary', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (262, 'Tax Accountant', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (263, 'Junior Executive', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (264, 'Clinical Specialist', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (265, 'Assistant Media Planner', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (266, 'Paralegal', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (267, 'Senior Financial Analyst', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (268, 'Developer III', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (269, 'Research Associate', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (270, 'Assistant Professor', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (271, 'Director of Sales', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (272, 'Teacher', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (273, 'Systems Administrator I', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (274, 'Junior Executive', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (275, 'Senior Editor', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (276, 'Recruiting Manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (277, 'Internal Auditor', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (278, 'Marketing Assistant', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (279, 'Research Associate', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (280, 'Occupational Therapist', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (281, 'Registered Nurse', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (282, 'Quality Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (283, 'Internal Auditor', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (284, 'Systems Administrator II', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (285, 'Software Consultant', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (286, 'Accounting Assistant II', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (287, 'Community Outreach Specialist', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (288, 'Paralegal', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (289, 'Health Coach II', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (290, 'Software Consultant', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (291, 'Business Systems Development Analyst', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (292, 'Assistant Manager', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (293, 'Librarian', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (294, 'VP Accounting', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (295, 'Quality Control Specialist', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (296, 'Analog Circuit Design manager', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (297, 'Dental Hygienist', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (298, 'Financial Advisor', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (299, 'Software Test Engineer III', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (300, 'Media Manager III', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (301, 'Registered Nurse', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (302, 'Office Assistant II', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (303, 'GIS Technical Architect', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (304, 'Accounting Assistant I', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (305, 'Environmental Tech', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (306, 'Senior Editor', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (307, 'GIS Technical Architect', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (308, 'Environmental Tech', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (309, 'Environmental Specialist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (310, 'Desktop Support Technician', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (311, 'Teacher', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (312, 'Registered Nurse', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (313, 'Programmer I', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (314, 'Associate Professor', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (315, 'Software Engineer I', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (316, 'Software Test Engineer IV', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (317, 'Computer Systems Analyst I', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (318, 'Actuary', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (319, 'Human Resources Assistant I', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (320, 'Research Associate', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (321, 'Help Desk Operator', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (322, 'Marketing Manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (323, 'Nurse Practicioner', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (324, 'Nurse Practicioner', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (325, 'Analyst Programmer', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (326, 'Nuclear Power Engineer', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (327, 'Geologist I', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (328, 'VP Sales', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (329, 'Physical Therapy Assistant', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (330, 'Senior Cost Accountant', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (331, 'Administrative Officer', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (332, 'VP Product Management', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (333, 'Nuclear Power Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (334, 'Systems Administrator III', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (335, 'Budget/Accounting Analyst I', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (336, 'Teacher', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (337, 'Accounting Assistant I', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (338, 'Community Outreach Specialist', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (339, 'Administrative Assistant II', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (340, 'Pharmacist', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (341, 'Product Engineer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (342, 'VP Quality Control', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (343, 'Technical Writer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (344, 'Design Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (345, 'Occupational Therapist', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (346, 'Social Worker', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (347, 'Account Executive', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (348, 'Administrative Assistant I', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (349, 'Chemical Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (350, 'Dental Hygienist', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (351, 'Analyst Programmer', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (352, 'General Manager', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (353, 'VP Product Management', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (354, 'Programmer III', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (355, 'Occupational Therapist', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (356, 'Financial Analyst', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (357, 'GIS Technical Architect', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (358, 'Nurse Practicioner', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (359, 'Physical Therapy Assistant', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (360, 'Civil Engineer', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (361, 'Cost Accountant', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (362, 'Clinical Specialist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (363, 'Structural Analysis Engineer', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (364, 'Engineer III', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (365, 'Budget/Accounting Analyst IV', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (366, 'Data Coordiator', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (367, 'Research Nurse', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (368, 'Clinical Specialist', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (369, 'Payment Adjustment Coordinator', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (370, 'Registered Nurse', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (371, 'Speech Pathologist', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (372, 'Mechanical Systems Engineer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (373, 'Web Designer I', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (374, 'Social Worker', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (375, 'Legal Assistant', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (376, 'Internal Auditor', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (377, 'Electrical Engineer', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (378, 'Recruiter', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (379, 'Software Test Engineer III', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (380, 'Web Developer II', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (381, 'Nurse', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (382, 'Web Designer I', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (383, 'Human Resources Assistant IV', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (384, 'Marketing Manager', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (385, 'Clinical Specialist', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (386, 'Dental Hygienist', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (387, 'Senior Editor', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (388, 'Accounting Assistant II', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (389, 'Senior Editor', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (390, 'Web Developer II', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (391, 'Web Designer III', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (392, 'Engineer IV', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (393, 'Senior Cost Accountant', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (394, 'Senior Editor', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (395, 'Software Engineer IV', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (396, 'Senior Editor', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (397, 'Electrical Engineer', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (398, 'Human Resources Manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (399, 'Web Developer I', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (400, 'Environmental Specialist', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (401, 'Assistant Professor', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (402, 'Account Executive', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (403, 'Quality Control Specialist', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (404, 'Help Desk Operator', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (405, 'Internal Auditor', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (406, 'Marketing Manager', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (407, 'Administrative Officer', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (408, 'Professor', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (409, 'Systems Administrator III', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (410, 'Technical Writer', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (411, 'Staff Scientist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (412, 'General Manager', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (413, 'Developer IV', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (414, 'Safety Technician II', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (415, 'Administrative Officer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (416, 'Nurse Practicioner', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (417, 'Cost Accountant', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (418, 'Legal Assistant', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (419, 'Sales Representative', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (420, 'Safety Technician I', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (421, 'Environmental Tech', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (422, 'Systems Administrator IV', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (423, 'Geological Engineer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (424, 'Payment Adjustment Coordinator', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (425, 'Compensation Analyst', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (426, 'Nurse', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (427, 'Assistant Manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (428, 'Accountant I', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (429, 'General Manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (430, 'Developer I', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (431, 'Electrical Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (432, 'Chemical Engineer', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (433, 'Social Worker', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (434, 'Graphic Designer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (435, 'Design Engineer', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (436, 'Financial Advisor', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (437, 'Database Administrator I', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (438, 'Assistant Manager', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (439, 'Marketing Assistant', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (440, 'Social Worker', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (441, 'Media Manager IV', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (442, 'VP Quality Control', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (443, 'VP Accounting', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (444, 'Senior Developer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (445, 'Payment Adjustment Coordinator', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (446, 'Software Engineer IV', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (447, 'Human Resources Assistant III', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (448, 'Financial Analyst', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (449, 'Product Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (450, 'Research Associate', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (451, 'Account Coordinator', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (452, 'Physical Therapy Assistant', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (453, 'Programmer Analyst IV', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (454, 'Chief Design Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (455, 'Teacher', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (456, 'Nuclear Power Engineer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (457, 'Web Designer IV', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (458, 'Registered Nurse', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (459, 'Mechanical Systems Engineer', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (460, 'Staff Scientist', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (461, 'Social Worker', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (462, 'Civil Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (463, 'Chief Design Engineer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (464, 'Media Manager I', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (465, 'Junior Executive', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (466, 'Financial Advisor', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (467, 'Programmer II', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (468, 'Internal Auditor', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (469, 'Structural Engineer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (470, 'Database Administrator IV', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (471, 'Assistant Manager', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (472, 'Professor', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (473, 'Data Coordiator', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (474, 'Electrical Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (475, 'Registered Nurse', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (476, 'Web Developer IV', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (477, 'Environmental Tech', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (478, 'Programmer Analyst IV', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (479, 'Web Developer I', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (480, 'VP Marketing', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (481, 'Registered Nurse', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (482, 'Chief Design Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (483, 'Computer Systems Analyst IV', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (484, 'Registered Nurse', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (485, 'VP Accounting', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (486, 'Speech Pathologist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (487, 'Design Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (488, 'Data Coordiator', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (489, 'Human Resources Manager', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (490, 'Paralegal', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (491, 'Financial Advisor', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (492, 'VP Quality Control', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (493, 'Analog Circuit Design manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (494, 'Product Engineer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (495, 'Accountant I', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (496, 'Marketing Manager', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (497, 'Analyst Programmer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (498, 'Account Coordinator', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (499, 'Structural Engineer', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (500, 'Editor', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (501, 'Recruiter', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (502, 'Staff Accountant IV', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (503, 'Accounting Assistant I', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (504, 'Structural Analysis Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (505, 'Tax Accountant', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (506, 'Community Outreach Specialist', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (507, 'VP Sales', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (508, 'VP Sales', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (509, 'Administrative Officer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (510, 'Environmental Specialist', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (511, 'Physical Therapy Assistant', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (512, 'Senior Financial Analyst', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (513, 'Staff Accountant I', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (514, 'Internal Auditor', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (515, 'Financial Analyst', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (516, 'Engineer II', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (517, 'Senior Quality Engineer', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (518, 'Help Desk Operator', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (519, 'Account Coordinator', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (520, 'Budget/Accounting Analyst II', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (521, 'Developer III', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (522, 'Quality Control Specialist', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (523, 'Business Systems Development Analyst', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (524, 'Analyst Programmer', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (525, 'Compensation Analyst', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (526, 'Senior Cost Accountant', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (527, 'Pharmacist', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (528, 'VP Accounting', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (529, 'Office Assistant III', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (530, 'Analyst Programmer', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (531, 'Senior Quality Engineer', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (532, 'Business Systems Development Analyst', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (533, 'Cost Accountant', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (534, 'Automation Specialist IV', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (535, 'Structural Analysis Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (536, 'Community Outreach Specialist', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (537, 'Structural Engineer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (538, 'General Manager', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (539, 'Accounting Assistant III', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (540, 'Programmer Analyst IV', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (541, 'Senior Editor', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (542, 'Environmental Specialist', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (543, 'Graphic Designer', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (544, 'VP Sales', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (545, 'Account Representative IV', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (546, 'Biostatistician II', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (547, 'Analyst Programmer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (548, 'Budget/Accounting Analyst IV', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (549, 'Structural Engineer', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (550, 'Statistician III', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (551, 'Senior Quality Engineer', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (552, 'Software Test Engineer I', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (553, 'Chief Design Engineer', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (554, 'Sales Associate', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (555, 'Senior Sales Associate', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (556, 'Office Assistant III', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (557, 'Biostatistician III', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (558, 'Developer I', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (559, 'Software Test Engineer IV', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (560, 'Media Manager IV', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (561, 'Programmer II', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (562, 'Help Desk Technician', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (563, 'Desktop Support Technician', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (564, 'Junior Executive', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (565, 'Office Assistant II', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (566, 'Account Representative IV', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (567, 'Junior Executive', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (568, 'Director of Sales', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (569, 'Nurse', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (570, 'Data Coordiator', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (571, 'Health Coach IV', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (572, 'Clinical Specialist', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (573, 'Professor', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (574, 'Geologist IV', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (575, 'Tax Accountant', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (576, 'Environmental Specialist', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (577, 'VP Sales', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (578, 'Senior Cost Accountant', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (579, 'Desktop Support Technician', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (580, 'General Manager', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (581, 'Help Desk Technician', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (582, 'VP Sales', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (583, 'Geological Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (584, 'Financial Analyst', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (585, 'Sales Representative', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (586, 'Actuary', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (587, 'Nuclear Power Engineer', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (588, 'Junior Executive', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (589, 'Clinical Specialist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (590, 'Occupational Therapist', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (591, 'Engineer I', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (592, 'Civil Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (593, 'Editor', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (594, 'Staff Scientist', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (595, 'Librarian', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (596, 'Quality Control Specialist', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (597, 'Mechanical Systems Engineer', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (598, 'Help Desk Technician', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (599, 'Chemical Engineer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (600, 'Statistician II', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (601, 'Senior Quality Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (602, 'Sales Representative', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (603, 'Registered Nurse', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (604, 'Compensation Analyst', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (605, 'Senior Developer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (606, 'Mechanical Systems Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (607, 'Paralegal', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (608, 'Biostatistician II', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (609, 'Clinical Specialist', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (610, 'Nurse Practicioner', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (611, 'Developer I', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (612, 'Desktop Support Technician', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (613, 'Structural Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (614, 'Recruiter', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (615, 'Staff Accountant II', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (616, 'Electrical Engineer', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (617, 'Data Coordiator', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (618, 'Administrative Officer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (619, 'Automation Specialist I', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (620, 'Senior Developer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (621, 'Geologist IV', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (622, 'Senior Editor', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (623, 'Sales Representative', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (624, 'Recruiting Manager', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (625, 'Financial Advisor', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (626, 'Graphic Designer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (627, 'Assistant Media Planner', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (628, 'Media Manager IV', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (629, 'Director of Sales', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (630, 'Research Associate', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (631, 'Account Coordinator', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (632, 'Legal Assistant', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (633, 'GIS Technical Architect', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (634, 'Environmental Specialist', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (635, 'Clinical Specialist', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (636, 'Accounting Assistant IV', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (637, 'VP Accounting', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (638, 'Design Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (639, 'Staff Accountant III', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (640, 'Help Desk Technician', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (641, 'Human Resources Manager', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (642, 'Compensation Analyst', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (643, 'Actuary', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (644, 'Analyst Programmer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (645, 'Civil Engineer', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (646, 'Registered Nurse', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (647, 'Account Executive', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (648, 'Budget/Accounting Analyst I', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (649, 'Research Nurse', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (650, 'Help Desk Operator', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (651, 'Analog Circuit Design manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (652, 'Compensation Analyst', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (653, 'Software Engineer I', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (654, 'Assistant Professor', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (655, 'Human Resources Manager', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (656, 'Accountant II', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (657, 'Financial Advisor', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (658, 'Technical Writer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (659, 'Account Coordinator', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (660, 'Business Systems Development Analyst', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (661, 'Teacher', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (662, 'Assistant Media Planner', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (663, 'Developer II', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (664, 'Electrical Engineer', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (665, 'Help Desk Operator', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (666, 'Biostatistician IV', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (667, 'Recruiter', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (668, 'Administrative Officer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (669, 'Assistant Professor', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (670, 'Registered Nurse', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (671, 'Product Engineer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (672, 'Registered Nurse', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (673, 'Programmer I', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (674, 'Editor', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (675, 'Social Worker', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (676, 'Structural Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (677, 'Senior Cost Accountant', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (678, 'Account Coordinator', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (679, 'Design Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (680, 'Assistant Professor', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (681, 'General Manager', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (682, 'Administrative Assistant II', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (683, 'Analyst Programmer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (684, 'Mechanical Systems Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (685, 'Office Assistant II', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (686, 'VP Sales', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (687, 'Business Systems Development Analyst', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (688, 'Assistant Manager', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (689, 'Health Coach I', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (690, 'VP Product Management', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (691, 'Nuclear Power Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (692, 'Account Representative II', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (693, 'Web Designer II', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (694, 'VP Accounting', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (695, 'Speech Pathologist', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (696, 'Help Desk Technician', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (697, 'Budget/Accounting Analyst III', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (698, 'Nurse Practicioner', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (699, 'Director of Sales', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (700, 'Community Outreach Specialist', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (701, 'Occupational Therapist', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (702, 'Financial Advisor', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (703, 'Structural Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (704, 'Junior Executive', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (705, 'Web Designer II', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (706, 'Computer Systems Analyst IV', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (707, 'Systems Administrator II', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (708, 'Assistant Professor', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (709, 'Teacher', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (710, 'Operator', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (711, 'Occupational Therapist', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (712, 'Environmental Tech', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (713, 'Compensation Analyst', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (714, 'GIS Technical Architect', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (715, 'Help Desk Technician', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (716, 'Account Executive', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (717, 'Health Coach II', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (718, 'Quality Engineer', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (719, 'Software Test Engineer III', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (720, 'VP Quality Control', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (721, 'Occupational Therapist', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (722, 'Financial Advisor', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (723, 'GIS Technical Architect', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (724, 'Civil Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (725, 'Statistician IV', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (726, 'Professor', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (727, 'Environmental Specialist', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (728, 'Marketing Manager', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (729, 'Accountant III', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (730, 'Pharmacist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (731, 'Information Systems Manager', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (732, 'Financial Analyst', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (733, 'Assistant Professor', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (734, 'Design Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (735, 'General Manager', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (736, 'Project Manager', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (737, 'Product Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (738, 'Financial Analyst', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (739, 'Staff Accountant IV', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (740, 'Speech Pathologist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (741, 'Computer Systems Analyst II', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (742, 'Research Nurse', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (743, 'Nurse', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (744, 'Executive Secretary', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (745, 'Marketing Manager', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (746, 'Editor', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (747, 'Chemical Engineer', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (748, 'Budget/Accounting Analyst II', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (749, 'Assistant Professor', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (750, 'Web Developer II', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (751, 'Marketing Manager', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (752, 'Software Test Engineer IV', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (753, 'Assistant Manager', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (754, 'Geologist IV', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (755, 'Mechanical Systems Engineer', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (756, 'Occupational Therapist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (757, 'Environmental Specialist', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (758, 'Staff Scientist', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (759, 'VP Marketing', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (760, 'Professor', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (761, 'Statistician III', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (762, 'VP Quality Control', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (763, 'Sales Representative', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (764, 'Office Assistant I', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (765, 'Food Chemist', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (766, 'Statistician IV', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (767, 'Environmental Tech', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (768, 'Registered Nurse', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (769, 'Chemical Engineer', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (770, 'Dental Hygienist', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (771, 'Business Systems Development Analyst', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (772, 'Marketing Assistant', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (773, 'Sales Associate', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (774, 'Software Consultant', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (775, 'Human Resources Manager', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (776, 'Nurse Practicioner', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (777, 'Desktop Support Technician', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (778, 'Project Manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (779, 'Media Manager I', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (780, 'Biostatistician III', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (781, 'Business Systems Development Analyst', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (782, 'Assistant Professor', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (783, 'Civil Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (784, 'Human Resources Manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (785, 'Nurse Practicioner', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (786, 'General Manager', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (787, 'Administrative Assistant II', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (788, 'Librarian', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (789, 'Product Engineer', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (790, 'Administrative Assistant II', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (791, 'Recruiter', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (792, 'Executive Secretary', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (793, 'Senior Quality Engineer', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (794, 'Payment Adjustment Coordinator', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (795, 'Senior Sales Associate', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (796, 'Operator', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (797, 'Civil Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (798, 'Clinical Specialist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (799, 'Programmer Analyst IV', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (800, 'Operator', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (801, 'Civil Engineer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (802, 'Associate Professor', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (803, 'Staff Scientist', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (804, 'Structural Analysis Engineer', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (805, 'Geological Engineer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (806, 'General Manager', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (807, 'Community Outreach Specialist', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (808, 'Compensation Analyst', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (809, 'Technical Writer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (810, 'Marketing Manager', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (811, 'Paralegal', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (812, 'Software Consultant', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (813, 'Programmer Analyst IV', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (814, 'Software Engineer II', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (815, 'Desktop Support Technician', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (816, 'Quality Control Specialist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (817, 'Librarian', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (818, 'Account Coordinator', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (819, 'Senior Sales Associate', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (820, 'Human Resources Manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (821, 'Computer Systems Analyst III', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (822, 'Administrative Assistant IV', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (823, 'Senior Editor', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (824, 'Quality Control Specialist', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (825, 'Cost Accountant', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (826, 'Sales Representative', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (827, 'Structural Engineer', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (828, 'VP Product Management', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (829, 'Compensation Analyst', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (830, 'Assistant Manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (831, 'Administrative Assistant IV', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (832, 'Computer Systems Analyst IV', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (833, 'Financial Analyst', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (834, 'Marketing Manager', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (835, 'Cost Accountant', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (836, 'VP Sales', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (837, 'Financial Advisor', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (838, 'Web Developer III', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (839, 'Recruiting Manager', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (840, 'Computer Systems Analyst I', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (841, 'Analog Circuit Design manager', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (842, 'Database Administrator IV', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (843, 'Associate Professor', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (844, 'Programmer I', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (845, 'Software Test Engineer III', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (846, 'Marketing Assistant', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (847, 'Biostatistician IV', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (848, 'Marketing Manager', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (849, 'Research Associate', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (850, 'Desktop Support Technician', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (851, 'Financial Analyst', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (852, 'Help Desk Operator', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (853, 'Environmental Specialist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (854, 'Budget/Accounting Analyst I', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (855, 'Desktop Support Technician', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (856, 'Geological Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (857, 'Nuclear Power Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (858, 'Media Manager III', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (859, 'Marketing Assistant', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (860, 'Technical Writer', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (861, 'Legal Assistant', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (862, 'Programmer Analyst II', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (863, 'Programmer Analyst III', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (864, 'Senior Sales Associate', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (865, 'Analog Circuit Design manager', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (866, 'VP Quality Control', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (867, 'VP Accounting', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (868, 'Research Nurse', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (869, 'Operator', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (870, 'Business Systems Development Analyst', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (871, 'Information Systems Manager', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (872, 'Recruiter', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (873, 'Electrical Engineer', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (874, 'VP Product Management', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (875, 'Biostatistician IV', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (876, 'Analyst Programmer', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (877, 'Nurse Practicioner', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (878, 'Technical Writer', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (879, 'Information Systems Manager', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (880, 'Senior Financial Analyst', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (881, 'Teacher', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (882, 'Sales Representative', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (883, 'Social Worker', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (884, 'Staff Scientist', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (885, 'Accounting Assistant I', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (886, 'Electrical Engineer', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (887, 'Quality Control Specialist', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (888, 'Associate Professor', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (889, 'Developer I', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (890, 'Assistant Media Planner', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (891, 'Director of Sales', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (892, 'Nurse', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (893, 'Nurse Practicioner', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (894, 'Librarian', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (895, 'Automation Specialist IV', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (896, 'Senior Financial Analyst', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (897, 'Programmer Analyst III', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (898, 'VP Marketing', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (899, 'Operator', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (900, 'Internal Auditor', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (901, 'Teacher', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (902, 'Account Coordinator', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (903, 'Dental Hygienist', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (904, 'Quality Control Specialist', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (905, 'Occupational Therapist', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (906, 'Nuclear Power Engineer', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (907, 'VP Quality Control', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (908, 'Teacher', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (909, 'Engineer II', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (910, 'Desktop Support Technician', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (911, 'Research Nurse', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (912, 'Junior Executive', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (913, 'Sales Representative', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (914, 'Research Associate', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (915, 'VP Quality Control', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (916, 'Engineer IV', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (917, 'Recruiting Manager', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (918, 'Editor', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (919, 'Editor', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (920, 'Structural Engineer', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (921, 'Mechanical Systems Engineer', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (922, 'Registered Nurse', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (923, 'Senior Sales Associate', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (924, 'Occupational Therapist', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (925, 'Account Executive', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (926, 'Geological Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (927, 'Programmer III', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (928, 'Human Resources Manager', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (929, 'Staff Accountant I', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (930, 'GIS Technical Architect', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (931, 'Teacher', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (932, 'Structural Analysis Engineer', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (933, 'Web Designer III', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (934, 'Chief Design Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (935, 'Accounting Assistant I', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (936, 'Nurse Practicioner', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (937, 'Assistant Manager', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (938, 'Design Engineer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (939, 'Statistician III', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (940, 'Human Resources Assistant IV', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (941, 'Senior Developer', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (942, 'Administrative Assistant III', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (943, 'VP Quality Control', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (944, 'Professor', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (945, 'Civil Engineer', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (946, 'Community Outreach Specialist', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (947, 'Assistant Manager', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (948, 'Director of Sales', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (949, 'Recruiting Manager', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (950, 'Associate Professor', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (951, 'Help Desk Technician', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (952, 'Senior Sales Associate', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (953, 'Office Assistant I', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (954, 'Registered Nurse', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (955, 'Teacher', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (956, 'Occupational Therapist', 6);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (957, 'Administrative Assistant I', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (958, 'Electrical Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (959, 'Biostatistician II', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (960, 'Accountant I', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (961, 'Marketing Manager', 10);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (962, 'Occupational Therapist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (963, 'Editor', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (964, 'Geologist I', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (965, 'Research Assistant III', 19);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (966, 'Statistician III', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (967, 'GIS Technical Architect', 8);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (968, 'Registered Nurse', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (969, 'Tax Accountant', 12);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (970, 'Human Resources Assistant I', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (971, 'Geological Engineer', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (972, 'Nurse Practicioner', 14);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (973, 'Software Test Engineer III', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (974, 'Occupational Therapist', 16);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (975, 'Nurse Practicioner', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (976, 'Assistant Manager', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (977, 'Recruiting Manager', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (978, 'Analyst Programmer', 11);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (979, 'Nurse', 1);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (980, 'Programmer Analyst II', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (981, 'Environmental Tech', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (982, 'VP Accounting', 20);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (983, 'Geological Engineer', 15);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (984, 'Pharmacist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (985, 'Food Chemist', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (986, 'Web Designer II', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (987, 'Design Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (988, 'Compensation Analyst', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (989, 'Registered Nurse', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (990, 'General Manager', 4);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (991, 'Senior Financial Analyst', 7);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (992, 'Assistant Manager', 2);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (993, 'Dental Hygienist', 18);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (994, 'Nuclear Power Engineer', 3);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (995, 'Speech Pathologist', 9);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (996, 'Senior Cost Accountant', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (997, 'Project Manager', 5);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (998, 'Assistant Professor', 17);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (999, 'Media Manager III', 13);
insert into EMPLOYEES_INSERT_SQL (emp_id, emp_role, prs_id) values (1000, 'VP Marketing', 4);
