insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Donald', 378, 'Kentucky', 'Louisville', 'Massachusetts');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Cascade', 155, 'Florida', 'Jacksonville', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Jana', 883, 'Ohio', 'Akron', 'Utah');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Pennsylvania', 207, 'Wisconsin', 'Madison', 'Maryland');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lawn', 86, 'Iowa', 'Des Moines', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mosinee', 457, 'California', 'Richmond', 'District of Columbia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Fair Oaks', 699, 'California', 'Torrance', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Bonner', 474, 'Texas', 'El Paso', 'North Dakota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Main', 549, 'California', 'San Diego', 'Idaho');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lawn', 221, 'New York', 'Rochester', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Transport', 714, 'Florida', 'Fort Lauderdale', 'North Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Springs', 714, 'Oklahoma', 'Tulsa', 'Tennessee');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Continental', 868, 'District of Columbia', 'Washington', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Vidon', 74, 'Washington', 'Spokane', 'Hawaii');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Bowman', 587, 'Florida', 'Jacksonville', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sunfield', 331, 'California', 'Irvine', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Straubel', 712, 'Ohio', 'Cleveland', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Armistice', 185, 'Michigan', 'Grand Rapids', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Fair Oaks', 471, 'California', 'Irvine', 'Iowa');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Village', 298, 'Oregon', 'Beaverton', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lakewood Gardens', 426, 'Virginia', 'Herndon', 'Missouri');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Raven', 74, 'Oklahoma', 'Oklahoma City', 'North Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Florence', 444, 'Missouri', 'Saint Louis', 'Oregon');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Ronald Regan', 762, 'California', 'Los Angeles', 'Michigan');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Farmco', 614, 'Florida', 'Miami Beach', 'West Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Anniversary', 394, 'Texas', 'Tyler', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mockingbird', 860, 'Texas', 'Dallas', 'Idaho');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Nancy', 559, 'Connecticut', 'Waterbury', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Pond', 539, 'Kentucky', 'Lexington', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Susan', 620, 'Tennessee', 'Nashville', 'Tennessee');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Reinke', 496, 'Connecticut', 'Danbury', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dexter', 712, 'Pennsylvania', 'Philadelphia', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hoepker', 322, 'Texas', 'El Paso', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Packers', 984, 'Colorado', 'Fort Collins', 'Iowa');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Veith', 433, 'Washington', 'Seattle', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Oneill', 132, 'Tennessee', 'Memphis', 'Ohio');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Walton', 96, 'Kentucky', 'Louisville', 'District of Columbia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Elmside', 250, 'Connecticut', 'Hartford', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('High Crossing', 10, 'Virginia', 'Roanoke', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Blackbird', 269, 'Florida', 'Miami', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Grim', 312, 'Alabama', 'Birmingham', 'Ohio');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Schlimgen', 814, 'California', 'Berkeley', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('East', 156, 'California', 'San Jose', 'Oklahoma');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Browning', 651, 'Pennsylvania', 'Erie', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mallard', 507, 'Georgia', 'Columbus', 'Colorado');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('East', 292, 'New York', 'Albany', 'Kansas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mayer', 439, 'Virginia', 'Norfolk', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sunfield', 219, 'Montana', 'Billings', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Prentice', 505, 'Pennsylvania', 'Pittsburgh', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Scofield', 825, 'North Carolina', 'Raleigh', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Pond', 873, 'Texas', 'San Antonio', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Forest Run', 884, 'Texas', 'Conroe', 'Louisiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dixon', 181, 'Alabama', 'Anniston', 'Nebraska');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Trailsway', 755, 'Iowa', 'Des Moines', 'North Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lillian', 428, 'Florida', 'Pensacola', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Northfield', 351, 'Mississippi', 'Jackson', 'Louisiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sutherland', 366, 'Ohio', 'Springfield', 'Tennessee');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mallory', 254, 'California', 'San Diego', 'Georgia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Raven', 595, 'Texas', 'El Paso', 'New Jersey');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Merry', 309, 'Florida', 'Orlando', 'Ohio');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Blaine', 103, 'Idaho', 'Idaho Falls', 'Pennsylvania');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Pierstorff', 435, 'California', 'Sacramento', 'South Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Stephen', 553, 'Missouri', 'Saint Louis', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Autumn Leaf', 754, 'District of Columbia', 'Washington', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Maywood', 539, 'Florida', 'Boynton Beach', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Westerfield', 33, 'Washington', 'Seattle', 'Washington');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Cambridge', 150, 'Virginia', 'Roanoke', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Prairie Rose', 86, 'Florida', 'Sarasota', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lakewood', 817, 'California', 'San Jose', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Jenifer', 351, 'Georgia', 'Duluth', 'Iowa');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Wayridge', 756, 'Texas', 'Dallas', 'Arizona');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Clyde Gallagher', 361, 'Texas', 'Fort Worth', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Stone Corner', 224, 'Nebraska', 'Lincoln', 'Wisconsin');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Jana', 718, 'Connecticut', 'Bridgeport', 'Mississippi');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Golf', 523, 'Texas', 'El Paso', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Division', 513, 'Florida', 'Naples', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Loomis', 364, 'Pennsylvania', 'Philadelphia', 'South Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Moulton', 540, 'Colorado', 'Denver', 'Alabama');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mayer', 473, 'South Carolina', 'Aiken', 'Oklahoma');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Roxbury', 387, 'Colorado', 'Denver', 'District of Columbia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Chive', 212, 'Minnesota', 'Saint Cloud', 'Indiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Arizona', 501, 'Georgia', 'Columbus', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Pleasure', 323, 'New Jersey', 'Trenton', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Manley', 692, 'Florida', 'Seminole', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Green Ridge', 919, 'Tennessee', 'Memphis', 'Georgia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Montana', 877, 'Kentucky', 'Louisville', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mcbride', 746, 'Virginia', 'Arlington', 'Nevada');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Drewry', 925, 'Nebraska', 'Omaha', 'North Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Ridge Oak', 75, 'Florida', 'Cape Coral', 'Colorado');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Brown', 407, 'Florida', 'Miami', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Spaight', 91, 'Florida', 'Pensacola', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Farragut', 51, 'California', 'Sacramento', 'Kansas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Roth', 998, 'West Virginia', 'Charleston', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Rusk', 510, 'Nevada', 'Sparks', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Golf View', 443, 'North Carolina', 'Wilmington', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Linden', 455, 'Georgia', 'Atlanta', 'Georgia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Banding', 447, 'Arizona', 'Phoenix', 'Connecticut');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dennis', 915, 'Arizona', 'Phoenix', 'North Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Nancy', 21, 'New Mexico', 'Santa Fe', 'Kansas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Banding', 512, 'Texas', 'Houston', 'Utah');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Clyde Gallagher', 780, 'North Carolina', 'Charlotte', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Fisk', 282, 'Pennsylvania', 'Harrisburg', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Anhalt', 656, 'Arkansas', 'Little Rock', 'Mississippi');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dunning', 881, 'California', 'Corona', 'Missouri');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Forster', 591, 'California', 'San Diego', 'New Hampshire');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Washington', 580, 'Arkansas', 'Fort Smith', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Nancy', 309, 'Tennessee', 'Knoxville', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Veith', 347, 'Ohio', 'Columbus', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Marquette', 981, 'Wisconsin', 'Madison', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Memorial', 572, 'Texas', 'Dallas', 'District of Columbia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Westend', 200, 'Arizona', 'Scottsdale', 'Delaware');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Pearson', 663, 'California', 'Sacramento', 'Arizona');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Kropf', 40, 'South Carolina', 'Charleston', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Buell', 384, 'Georgia', 'Albany', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Scott', 125, 'South Carolina', 'Greenville', 'Maryland');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sunnyside', 715, 'California', 'Sacramento', 'Washington');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Pepper Wood', 968, 'Indiana', 'Evansville', 'Oklahoma');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Independence', 5, 'District of Columbia', 'Washington', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Gina', 353, 'California', 'Sacramento', 'Idaho');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Golf View', 966, 'California', 'Northridge', 'New Jersey');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Holmberg', 45, 'Texas', 'Huntsville', 'Iowa');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Morning', 812, 'New York', 'New York City', 'Pennsylvania');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Towne', 689, 'West Virginia', 'Huntington', 'Ohio');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Westridge', 29, 'Texas', 'El Paso', 'North Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sundown', 336, 'Georgia', 'Atlanta', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Nobel', 721, 'Michigan', 'Detroit', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mesta', 257, 'California', 'Concord', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('5th', 357, 'Tennessee', 'Memphis', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Oneill', 53, 'California', 'Sacramento', 'Massachusetts');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Clyde Gallagher', 167, 'Virginia', 'Norfolk', 'New Hampshire');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Kings', 637, 'California', 'San Diego', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Manley', 965, 'Illinois', 'Peoria', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Anhalt', 518, 'Texas', 'Midland', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Arizona', 306, 'Missouri', 'Saint Louis', 'Oklahoma');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Fallview', 57, 'Texas', 'El Paso', 'Massachusetts');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Anniversary', 962, 'Oregon', 'Portland', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Debra', 783, 'California', 'San Jose', 'Georgia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Roxbury', 206, 'California', 'Sacramento', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Novick', 721, 'New York', 'Rochester', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Talisman', 853, 'South Dakota', 'Sioux Falls', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Oneill', 957, 'Utah', 'Salt Lake City', 'Delaware');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dunning', 597, 'Texas', 'San Angelo', 'Washington');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Green Ridge', 508, 'Kentucky', 'Lexington', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Continental', 645, 'New York', 'New York City', 'Connecticut');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Esch', 108, 'Pennsylvania', 'Erie', 'Ohio');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hanson', 679, 'Illinois', 'Decatur', 'Connecticut');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hintze', 450, 'Washington', 'Kent', 'Wisconsin');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Kinsman', 574, 'Ohio', 'Cincinnati', 'Michigan');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Londonderry', 520, 'California', 'Concord', 'Massachusetts');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Barnett', 457, 'California', 'San Francisco', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Delladonna', 429, 'Indiana', 'Indianapolis', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Talisman', 659, 'Florida', 'Panama City', 'Alabama');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Daystar', 92, 'California', 'Sacramento', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Melby', 862, 'Georgia', 'Macon', 'Arizona');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hanover', 757, 'Texas', 'Austin', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Melby', 303, 'Illinois', 'Chicago', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lien', 423, 'Florida', 'Orlando', 'District of Columbia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Grayhawk', 317, 'New York', 'Syracuse', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Bluejay', 496, 'Washington', 'Spokane', 'Pennsylvania');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Porter', 44, 'Missouri', 'Saint Louis', 'Utah');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Prentice', 128, 'Texas', 'Fort Worth', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Morrow', 575, 'California', 'Pasadena', 'Pennsylvania');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('South', 349, 'Florida', 'Tampa', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Judy', 960, 'Alabama', 'Tuscaloosa', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Oneill', 622, 'New Mexico', 'Albuquerque', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Straubel', 448, 'Connecticut', 'New Haven', 'Wisconsin');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Crest Line', 456, 'Virginia', 'Herndon', 'Alaska');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Anniversary', 717, 'Louisiana', 'Baton Rouge', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Maple', 343, 'Florida', 'Orlando', 'Kansas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Division', 657, 'South Carolina', 'Spartanburg', 'Wisconsin');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hermina', 975, 'District of Columbia', 'Washington', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Melody', 254, 'New York', 'New York City', 'West Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('5th', 470, 'North Carolina', 'Winston Salem', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Becker', 566, 'New York', 'Albany', 'Michigan');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Eliot', 913, 'Texas', 'El Paso', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Oak', 391, 'Missouri', 'Springfield', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Ronald Regan', 611, 'Nebraska', 'Lincoln', 'Hawaii');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sullivan', 866, 'California', 'Northridge', 'Ohio');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Jana', 406, 'Missouri', 'Saint Louis', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mallory', 235, 'Tennessee', 'Chattanooga', 'Missouri');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Cambridge', 42, 'Louisiana', 'Baton Rouge', 'District of Columbia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Bayside', 999, 'Florida', 'Fort Lauderdale', 'Kentucky');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Bayside', 315, 'Virginia', 'Richmond', 'Arizona');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Memorial', 21, 'Texas', 'Midland', 'Kentucky');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Spenser', 728, 'Colorado', 'Boulder', 'Michigan');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Menomonie', 37, 'Missouri', 'Kansas City', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Longview', 474, 'Texas', 'Corpus Christi', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Muir', 926, 'Nevada', 'Las Vegas', 'Indiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Duke', 655, 'California', 'Sacramento', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Calypso', 549, 'Utah', 'Salt Lake City', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mayfield', 483, 'North Carolina', 'Greensboro', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('3rd', 132, 'Michigan', 'Southfield', 'Georgia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sloan', 641, 'Georgia', 'Savannah', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Waywood', 962, 'Alabama', 'Mobile', 'Maryland');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Grim', 775, 'New York', 'New York City', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hovde', 894, 'New York', 'New York City', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hanson', 200, 'Kansas', 'Shawnee Mission', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Orin', 388, 'Texas', 'Temple', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Fuller', 780, 'Georgia', 'Columbus', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Parkside', 773, 'Ohio', 'Cincinnati', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Holmberg', 55, 'Colorado', 'Denver', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Shopko', 692, 'Michigan', 'Detroit', 'Kentucky');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Oak', 555, 'Kansas', 'Wichita', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lawn', 548, 'Georgia', 'Decatur', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Charing Cross', 473, 'Ohio', 'Columbus', 'West Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Ridge Oak', 63, 'Arizona', 'Phoenix', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Canary', 879, 'Kansas', 'Topeka', 'Michigan');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Boyd', 383, 'California', 'Bakersfield', 'Nevada');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Carberry', 247, 'District of Columbia', 'Washington', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Ridge Oak', 366, 'Texas', 'Abilene', 'Arkansas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Donald', 187, 'North Carolina', 'High Point', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lakewood', 38, 'New Mexico', 'Albuquerque', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Continental', 627, 'Georgia', 'Savannah', 'Colorado');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Bunker Hill', 844, 'District of Columbia', 'Washington', 'Delaware');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Esker', 930, 'Alabama', 'Montgomery', 'District of Columbia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Becker', 813, 'Florida', 'Panama City', 'Alabama');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Derek', 613, 'Washington', 'Seattle', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Forest Dale', 393, 'Texas', 'Houston', 'Connecticut');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Ryan', 278, 'Florida', 'West Palm Beach', 'Nebraska');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Twin Pines', 8, 'Oklahoma', 'Oklahoma City', 'Wyoming');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mayfield', 312, 'Virginia', 'Alexandria', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Nancy', 195, 'Texas', 'El Paso', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Milwaukee', 172, 'New York', 'New York City', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Tomscot', 723, 'New York', 'Jamaica', 'Alabama');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sunbrook', 993, 'Texas', 'Texarkana', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Comanche', 63, 'Colorado', 'Pueblo', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Porter', 163, 'Tennessee', 'Memphis', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Briar Crest', 726, 'Alaska', 'Anchorage', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Bonner', 93, 'Indiana', 'Terre Haute', 'Massachusetts');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Crownhardt', 392, 'North Carolina', 'Charlotte', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Merry', 551, 'Mississippi', 'Hattiesburg', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Stone Corner', 809, 'Indiana', 'Indianapolis', 'Massachusetts');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Holy Cross', 825, 'Missouri', 'Kansas City', 'New Jersey');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Gateway', 500, 'Florida', 'Sarasota', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Kenwood', 747, 'Georgia', 'Atlanta', 'Tennessee');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Spohn', 824, 'Oklahoma', 'Tulsa', 'Pennsylvania');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Park Meadow', 405, 'South Carolina', 'Columbia', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Russell', 118, 'Florida', 'Pensacola', 'Indiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dahle', 106, 'Texas', 'Houston', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Meadow Valley', 647, 'New York', 'White Plains', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Granby', 796, 'Mississippi', 'Jackson', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mayfield', 175, 'Wisconsin', 'Milwaukee', 'Washington');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Village Green', 715, 'California', 'Sacramento', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Cardinal', 153, 'Alabama', 'Birmingham', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Briar Crest', 919, 'Delaware', 'Wilmington', 'New Mexico');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Gina', 871, 'California', 'San Rafael', 'Colorado');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Sullivan', 809, 'Alaska', 'Juneau', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Arkansas', 382, 'California', 'Los Angeles', 'Wisconsin');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hermina', 289, 'Florida', 'Miami', 'District of Columbia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Emmet', 894, 'Texas', 'Tyler', 'Georgia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Gina', 288, 'Maryland', 'Silver Spring', 'Montana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Spohn', 200, 'Maryland', 'Bowie', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('4th', 433, 'Tennessee', 'Jackson', 'Louisiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lotheville', 586, 'Georgia', 'Atlanta', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Shelley', 329, 'California', 'Riverside', 'Washington');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('John Wall', 703, 'Colorado', 'Colorado Springs', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mitchell', 854, 'Nevada', 'Las Vegas', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Derek', 607, 'District of Columbia', 'Washington', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dryden', 281, 'Texas', 'San Antonio', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Service', 766, 'New York', 'Albany', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Norway Maple', 128, 'Massachusetts', 'Boston', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Ludington', 837, 'Alabama', 'Birmingham', 'Pennsylvania');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Becker', 808, 'Florida', 'Jacksonville', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Larry', 937, 'Florida', 'Port Charlotte', 'Illinois');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Loomis', 879, 'Arizona', 'Tucson', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Merchant', 889, 'Virginia', 'Suffolk', 'Ohio');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Hermina', 201, 'California', 'San Francisco', 'Iowa');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Manitowish', 342, 'Florida', 'Spring Hill', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mesta', 884, 'Utah', 'Salt Lake City', 'Missouri');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dexter', 204, 'Florida', 'Sarasota', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Redwing', 383, 'Ohio', 'Dayton', 'California');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Oriole', 171, 'Florida', 'Pensacola', 'Alabama');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Mandrake', 217, 'South Dakota', 'Sioux Falls', 'Wisconsin');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Randy', 495, 'Indiana', 'Indianapolis', 'Kansas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Annamark', 901, 'New York', 'Syracuse', 'Louisiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Nova', 468, 'California', 'Sacramento', 'New York');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dahle', 92, 'Oklahoma', 'Oklahoma City', 'Missouri');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Little Fleur', 73, 'North Carolina', 'Charlotte', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Declaration', 557, 'Alabama', 'Gadsden', 'Alabama');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Manitowish', 640, 'Georgia', 'Columbus', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Fair Oaks', 431, 'Missouri', 'Saint Louis', 'Louisiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('East', 735, 'Ohio', 'Akron', 'Louisiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Porter', 374, 'Kansas', 'Wichita', 'Pennsylvania');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Westerfield', 851, 'Florida', 'Miami', 'North Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Harper', 974, 'Kansas', 'Topeka', 'Montana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Burrows', 321, 'Nevada', 'Las Vegas', 'Washington');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Logan', 162, 'California', 'Long Beach', 'Maryland');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Fisk', 190, 'New York', 'Brooklyn', 'Ohio');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Westport', 349, 'Hawaii', 'Honolulu', 'New Jersey');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Cordelia', 259, 'Georgia', 'Decatur', 'Florida');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Dexter', 865, 'New Jersey', 'Newark', 'Louisiana');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Anzinger', 136, 'Iowa', 'Des Moines', 'Pennsylvania');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Northview', 376, 'District of Columbia', 'Washington', 'Minnesota');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Steensland', 224, 'Texas', 'Spring', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Oak Valley', 717, 'South Dakota', 'Sioux Falls', 'South Carolina');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Vernon', 640, 'Florida', 'Punta Gorda', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Lunder', 271, 'New York', 'New York City', 'Mississippi');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Ilene', 362, 'California', 'Fresno', 'Texas');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('Veith', 48, 'California', 'San Diego', 'Virginia');
insert into tbl_address (ads_street_name, ads_number, ads_neighborhood, ads_city, ads_state) values ('West', 193, 'Missouri', 'Springfield', 'Texas');
